{% set name = "coffea" %}
{% set version = "2024.8.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coffea-{{ version }}.tar.gz
  sha256: e521f5595d90eca3dc6a24e91f7b17cde7da5e017b1d2c7875c89bdb6536da2d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - hatchling >=1.17.1
    - hatch-vcs
    - pip
  run:
    - python >=3.8
    - awkward >=2.6.7
    - uproot >=5.3.11
    - dask-core >=2024.3.0
    - dask-awkward >=2024.3.0
    - dask-histogram >=2024.3.0
    - vector >=1.4.1
    - correctionlib >=2.6.0
    - pyarrow >=6.0.0
    - matplotlib-base >=3
    - numba >=0.58.1
    - numpy >=1.22.0
    - scipy >=1.1.0
    - tqdm >=4.27.0
    - lz4
    - cloudpickle >=1.2.3
    - toml >=0.10.2
    - mplhep >=0.1.18
    - packaging
    - pandas
    - hist >=2
    - cachetools

test:
  imports:
    - coffea
  requires:
    - pip

about:
  home: https://github.com/CoffeaTeam/coffea
  summary: Tools for doing Collider HEP style analysis with columnar operations
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lgray
    - nsmith-
    - areinsvo
    - mcremone
    - chrisburr
    - henryiii
