{% set name = "coffea" %}
{% set version = "2025.1.1" %}
{% set python_min = "3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/coffea-{{ version }}.tar.gz
  sha256: 0744b1c951973951bacb48708e37fe481697f696aa1b89c28db4a9cfc2ce26d6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.17.1
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - awkward >=2.6.7
    - uproot >=5.3.11
    - dask-core >=2024.3.0
    - dask-awkward >=2024.9.0
    - dask-histogram >=2024.9.1
    - vector >=1.4.1
    - correctionlib >=2.6.0
    - pyarrow >=6.0.0
    - fsspec-xrootd >=0.2.3
    - matplotlib-base >=3
    - numba >=0.58.1
    - numpy >=1.22.0
    - scipy >=1.1.0
    - tqdm >=4.27.0
    - lz4
    - cloudpickle >=1.2.3
    - toml >=0.10.2
    - mplhep >=0.1.18
    - packaging
    - pandas
    - hist >=2
    - cachetools
    - requests
    - aiohttp

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - coffea
  commands:
    - pip check

about:
  home: https://github.com/CoffeaTeam/coffea
  summary: Tools for doing Collider HEP style analysis with columnar operations
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://coffea-hep.readthedocs.io/
  dev_url: https://github.com/CoffeaTeam/coffea

extra:
  recipe-maintainers:
    - lgray
    - nsmith-
    - areinsvo
    - mcremone
    - chrisburr
    - henryiii
    - conda-forge/scikit-hep
