{% set name = "coffea" %}
{% set version = "2024.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coffea-{{ version }}.tar.gz
  sha256: 73f6fd0e77a1f5cb31299c10cbbb600b7d458eb16990b05f85f064d3f404e004

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - hatchling >=1.17.1
    - hatch-vcs
    - pip
  run:
    - python >=3.8
    - awkward >=2.5.2
    - uproot >=5.2.2
    - dask-core >=2023.4.0
    - dask-awkward >=2024.2.0
    - dask-histogram >=2024.2.0
    - correctionlib >=2.3.3
    - pyarrow >=6.0.0
    - matplotlib-base >=3
    - numba >=0.58.1
    - numpy >=1.22.0
    - scipy >=1.1.0
    - tqdm >=4.27.0
    - lz4
    - cloudpickle >=1.2.3
    - toml >=0.10.2
    - mplhep >=0.1.18
    - packaging
    - pandas
    - hist >=2
    - cachetools

test:
  imports:
    - coffea
  requires:
    - pip

about:
  home: https://github.com/CoffeaTeam/coffea
  summary: Tools for doing Collider HEP style analysis with columnar operations
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lgray
    - nsmith-
    - areinsvo
    - mcremone
    - chrisburr
    - henryiii
