{% set name = "coffea" %}
{% set version = "0.7.16" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coffea-{{ version }}.tar.gz
  sha256: ff2335531e2087d33f2622c5841b9d973b6b50759fe5c72dd1a33d896b6d4b99

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - awkward >=1.5.1,<2
    - cachetools
    - cloudpickle >=1.2.3
    - correctionlib >=2.0.0
    - dataclasses  # [py<37]
    - fsspec
    - hist >=2
    - lz4
    - matplotlib-base >=3
    - mplhep >=0.1.18
    - numba >=0.50.0
    - numpy >=1.16.0,<1.22
    - packaging
    - pandas
    - pyarrow >=1.0.0
    - python
    - scipy >=1.1.0
    - toml >=0.10.2
    - tqdm >=4.27.0
    - typing-extensions  # [py<38]
    - uproot >=4.1.6,<5,!=4.2.4,!=4.3.0,!=4.3.1
    - uproot3 >=3.14.1
    - uproot3-methods >=0.10.0

test:
  imports:
    - coffea
    - coffea.processor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CoffeaTeam/coffea
  summary: Tools for doing Collider HEP style analysis with columnar operations
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lgray
    - nsmith-
    - areinsvo
    - mcremone
    - chrisburr
