{% set name = "coffea" %}
{% set version = "0.7.22" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coffea-{{ version }}.tar.gz
  sha256: 19663ad442ede36d61b2aeab1fabb3369588af8871ccb0c09c2d19a41d95b0d9
build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - awkward >=1.10.3,<2
    - cachetools
    - cloudpickle >=1.2.3
    - correctionlib >=2.0.0
    - fsspec
    - hist >=2
    - lz4
    - matplotlib-base >=3
    - mplhep >=0.1.18
    - numba
    - numpy >=1.18
    - packaging
    - pandas
    - pyarrow >=1.0.0
    - python >=3.7
    - scipy >=1.1.0
    - toml >=0.10.2
    - tqdm >=4.27.0
    - typing-extensions
    - uproot >=4.1.6,<5,!=4.2.4,!=4.3.0,!=4.3.1
    - uproot3 >=3.14.1
    - uproot3-methods >=0.10.0

test:
  imports:
    - coffea
    - coffea.processor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CoffeaTeam/coffea
  summary: Tools for doing Collider HEP style analysis with columnar operations
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lgray
    - nsmith-
    - areinsvo
    - mcremone
    - chrisburr
    - henryiii
